Feature/psm
vortexntnu/vortex-asv pull request #108
Opened 2023-11-01 20:05 UTC by RoseKapps

PSM finished and tested
the i2c need to be physically fixed
just need to add README file

2023-11-01 20:45 UTC, PizzaAllTheWay requested changes
Overal very good job Rose. Just need to dlete some stuff and add a README.md file and you are good ^-^

2023-11-01 20:45 UTC, PizzaAllTheWay commented on key
Delete this file

2023-11-01 20:45 UTC, PizzaAllTheWay commented on key.pub
Delete this file

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/internal_status/power_sense_module_lib.py
> +        #time.sleep(1)
Delete the "time.sleep(1)" coment

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/internal_status/power_sense_module_publisher.py
> +        self.i = 0
remove unecessary variable self.i as it serves no purpose

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/internal_status/power_sense_module_publisher.py
> +        self.i += 1
remove unecessary variable self.i as it serves no purpose

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/test/test_copyright.py
Do we need this file?

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/test/test_flake8.py
Do we need this file?

2023-11-01 20:45 UTC, PizzaAllTheWay commented on mission/internal_status/test/test_pep257.py
Do we need this file?

2023-11-05 22:50 UTC, chrstrom commented on mission/internal_status/test/test_pep257.py
Might want to handover to devops, to make flake8, pep257 and mypy checks run on all files across this repo 😉

2023-11-05 22:54 UTC, chrstrom commented on mission/internal_status/internal_status/power_sense_module_lib.py
> +            return
You could avoid a bit of copy paste / nesting here by adding a decorator, f.ex:

```python
def io_error_safe_read(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except IOError:
            return
    return wrapper
```

then:

```python
    @io_error_safe_read
    def get_voltage(self):
        system_voltage = (self.channel_voltage.convert_and_read() *
                          self.psm_to_battery_voltage)
        return system_voltage

    @io_error_safe_read
    def get_current(self):
        system_current = (self.channel_current.convert_and_read() - 
                          self.psm_to_battery_current_offset
                         ) * self.psm_to_battery_current_scale_factor
        return system_current
```

2023-11-05 22:56 UTC, chrstrom commented on mission/internal_status/internal_status/power_sense_module_publisher.py
> +class MinimalPublisher(Node):
Would rename this to something a bit more descriptive 🐱

2023-11-06 04:23 UTC, PizzaAllTheWay commented on mission/internal_status/test/test_pep257.py
@FabianKongelf DevOps project O-O <3

2023-11-06 04:40 UTC, PizzaAllTheWay requested changes
Verry well done. 
Verry IMPORTANT that you delete the "key" and "key.gen" files as I can connect to you git acount and push code wothout your concent and without knowing your password. I sugest you also disable this key just in case and make one private and write it down somewhere :)

If you want to further improve PSM system you can try and implement what Cristopher has commented. But that is ONLY if you feel confident that you know how to do those changes, otherwise no further improvements needed, this is a good code for me :)

2023-11-06 04:40 UTC, PizzaAllTheWay commented on key
@RoseKapps Delete this file

2023-11-06 04:40 UTC, PizzaAllTheWay commented on key.pub
@RoseKapps Delete this file

2023-11-12 13:34 UTC, PizzaAllTheWay approved these changes
Verry nice jesjes

2023-11-12 13:38 UTC, merged