Feature/add stim300 driver
vortexntnu/Vortex-ASV pull request #23
Opened 2022-01-27 19:09 UTC by VNaas

Stim300 works

2022-01-29 14:58 UTC, chrstrom requested changes
Nice! I like the Vortex-AUV style dependencies setup. Just a minor change req before accepting

2022-01-29 14:58 UTC, chrstrom commented on Dockerfile
```suggestion
RUN chown vortex /home/vortex/asv_ws
RUN chmod a+rw /dev/ttyUSB*

```

Will give permission to all currently connected USB devices

2022-01-30 13:35 UTC, ronjakr approved these changes
lgtm

2022-01-30 13:45 UTC, chrstrom approved these changes
lgtm

2022-01-30 13:45 UTC, merged