Feature/#61 colav
vortexntnu/vortex-asv pull request #81
Opened 2023-04-28 13:05 UTC by oskarhelgerud890

Implemented functionality for COLAV, works in simulations
Implemented a flipper between LOS and COLAV
Needs testing on hardware

2023-04-29 14:44 UTC, theBadMusician requested changes
I am using code in VOMATH is fuunctional and that FSM code has been tested. Needs to be cleaned up and unnecessary code removed.

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VOMATH.py
> +#     return velocity.value
Remove is code is not going to be used

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VOMATH.py
> +        #implement landmar server
Complete the function or explain why it does not do anything (a TODO?), or remove if it is not needed

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VOMATH.py
> +if __name__ == "__main__":
Remove comments if not to be used. What is this main supposed to do?

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        rospy.init_node("colav",anonymous=True)
anonymous = false

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        and sending it to the AUV's velocity controller. This is implemented as a service that
ASV

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        and sending it to the AUV's velocity controller. This is implemented as a service that
We do not have a velocity controller, but we have a surge controller (named speed controller), and also a heading controller

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        VO = VelocityObstacle(None,self.obstacle,self.vessel) #Placeholder None
What is the None?

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        while VO.check_if_collision():
maybe change function name to is_collision, this way, the return value is true if collision and false if not collision. Makes code mroe readable

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_controller_node.py
> +        pass
do not need try and except, use while not rospy is shutdown instead.

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VO_visualize.py
Add some comments in the code and remove commented out code .

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VOMATH.py
This file should just be a library python file that gets imported where needed, without any ROS code.

2023-04-29 14:44 UTC, theBadMusician commented on motion/colav/scripts/VOMATH.py
rename to VO_math

2023-04-29 14:44 UTC, theBadMusician commented on motion/los_guidance/scripts/los_guidance_node.py
>      Nodes created:
Why has this been deleted? Revert maybe, and this is crazy, but heres my number, so call me maybe

2023-04-29 14:44 UTC, theBadMusician commented on motion/los_guidance/scripts/los_guidance_node.py
> +        #placeholder srv name
remove placeholder comment

2023-04-29 14:44 UTC, theBadMusician commented on motion/los_guidance/scripts/los_guidance_node.py
> +
remove whitespace

2023-04-29 14:45 UTC, theBadMusician requested changes
I am using code in VOMATH is fuunctional and that FSM code has been tested. Needs to be cleaned up and unnecessary code removed.

2023-05-12 14:10 UTC, EliasAarekol commented
⢿⣿⣿⣿⣭⠹⠛⠛⠛⢿⣿⣿⣿⣿⡿⣿⠷⠶⠿⢻⣿⣛⣦⣙⠻⣿
⣿⣿⢿⣿⠏⠀⠀⡀⠀⠈⣿⢛⣽⣜⠯⣽⠀⠀⠀⠀⠙⢿⣷⣻⡀⢿
⠐⠛⢿⣾⣖⣤⡀⠀⢀⡰⠿⢷⣶⣿⡇⠻⣖⣒⣒⣶⣿⣿⡟⢙⣶⣮
⣤⠀⠀⠛⠻⠗⠿⠿⣯⡆⣿⣛⣿⡿⠿⠮⡶⠼⠟⠙⠊⠁⠀⠸⢣⣿
⣿⣷⡀⠀⠀⠀⠀⠠⠭⣍⡉⢩⣥⡤⠥⣤⡶⣒⠀⠀⠀⠀⠀⢰⣿⣿
⣿⣿⡽⡄⠀⠀⠀⢿⣿⣆⣿⣧⢡⣾⣿⡇⣾⣿⡇⠀⠀⠀⠀⣿⡇⠃
⣿⣿⣷⣻⣆⢄⠀⠈⠉⠉⠛⠛⠘⠛⠛⠛⠙⠛⠁⠀⠀⠀⠀⣿⡇⢸
⢞⣿⣿⣷⣝⣷⣝⠦⡀⠀⠀⠀⠀⠀⠀⠀⡀⢀⠀⠀⠀⠀⠀⠛⣿⠈
⣦⡑⠛⣟⢿⡿⣿⣷⣝⢧⡀⠀⠀⣶⣸⡇⣿⢸⣧⠀⠀⠀⠀⢸⡿⡆
⣿⣿⣷⣮⣭⣍⡛⠻⢿⣷⠿⣶⣶⣬⣬⣁⣉⣀⣀⣁⡤⢴⣺⣾⣽⡇

wrong branch hehe, see new pull req

2023-05-12 14:12 UTC, closed without merging